name: Mixer
description: Crypto asset porfolio allocation
author: Alan
email: alan@longmire.io

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.2.0

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  english_words: ^3.1.5
  shared_preferences: ^0.5.7+3
  fluttertoast: ^4.0.1
  liquid_pull_to_refresh: ^2.0.0
  http: ^0.12.1
  pointycastle: ^1.0.2
  crypto: ^2.1.4
  page_transition: ^1.1.5
  hex: ^0.1.2
  http_auth: ^0.2.9

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_launcher_icons: ^0.7.0
  flutter_test:
    sdk: flutter
  shelf: ^0.7.5
  shelf_router: ^0.7.2
  shelf_proxy: ^0.1.0+7


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/coinbase.png
    - assets/coinbase_pro.jpg
    - assets/binance.png
    - assets/bittrex.jpg
    - assets/mercatox.png
    - assets/hitbtc.png
    - assets/kraken.png

flutter_icons:
  android: ic_app
  ios: true
  image_path: assets/app.png
